-- Drop the table if it exists to reset schema
DROP TABLE IF EXISTS reddit_safe_embeddings;

-- Create the table with all required columns, including emotion_label
CREATE TABLE reddit_safe_embeddings (
    id bigint generated by default as identity primary key,
    post_id text,
    chunk_id int,
    author text,
    created_utc float,
    score int,
    subreddit text,
    title text,
    input text, -- The chunked text
    input_tokens int,
    embedding vector(1536), -- Adjust dimension if using a different model
    label text,
    emotion_label text, -- Predicted emotion from probe
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_reddit_safe_label ON reddit_safe_embeddings(label);
CREATE INDEX IF NOT EXISTS idx_reddit_safe_subreddit ON reddit_safe_embeddings(subreddit);
CREATE INDEX IF NOT EXISTS idx_reddit_safe_post_id ON reddit_safe_embeddings(post_id);
CREATE INDEX IF NOT EXISTS idx_reddit_safe_emotion ON reddit_safe_embeddings(emotion_label);

-- Enable RLS and policies for the safe table
ALTER TABLE public.reddit_safe_embeddings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-only access" ON public.reddit_safe_embeddings FOR SELECT USING (true);
CREATE POLICY "Allow insert for authenticated users only" ON public.reddit_safe_embeddings FOR INSERT TO authenticated WITH CHECK (true);

