-- Drop the table if it exists to reset schema
DROP TABLE IF EXISTS wildchat_embeddings;

-- Create the table with all required columns
CREATE TABLE wildchat_embeddings (
    id bigint generated by default as identity primary key,
    conversation_hash text,
    turn_id int,
    chunk_id int,
    model text,
    language text,
    input text, -- The user input chunk
    output text, -- The assistant response (context)
    input_tokens int,
    embedding vector(1536), -- Using large model reduced to 1536
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_wildchat_hash ON wildchat_embeddings(conversation_hash);

-- Enable RLS and policies
ALTER TABLE public.wildchat_embeddings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-only access" ON public.wildchat_embeddings FOR SELECT USING (true);
CREATE POLICY "Allow insert for authenticated users only" ON public.wildchat_embeddings FOR INSERT TO authenticated WITH CHECK (true);

