-- Drop the table if it exists to reset schema
DROP TABLE IF EXISTS goemotions_embeddings;

-- Create the table with all required columns
CREATE TABLE goemotions_embeddings (
    id bigint generated by default as identity primary key,
    post_id text,
    chunk_id int,
    subreddit text,
    input text, -- The chunked text
    emotions text[], -- Array of emotion labels
    input_tokens int,
    embedding vector(1536), -- Using large model reduced to 1536
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_goemotions_post_id ON goemotions_embeddings(post_id);

-- Enable RLS and policies
ALTER TABLE public.goemotions_embeddings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-only access" ON public.goemotions_embeddings FOR SELECT USING (true);
CREATE POLICY "Allow insert for authenticated users only" ON public.goemotions_embeddings FOR INSERT TO authenticated WITH CHECK (true);

